<a href="https://colab.research.google.com/github/melinalessa/AnaliseExploratoriaPandas/blob/main/exe7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importando Biblioteca

In [1]:
import pandas as pd

Criar Vari√°vel

In [4]:
df= pd.read_csv('FAOSTAT_data_12-5-2020.csv')
df

,Domain Code,Domain,Area Code,Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,QC,Crops,9,Argentina,5419,Yield,515,Apples,2016,2016,hg/ha,223912,Fc,Calculated data
1,QC,Crops,9,Argentina,5419,Yield,515,Apples,2017,2017,hg/ha,235386,Fc,Calculated data
2,QC,Crops,9,Argentina,5419,Yield,515,Apples,2018,2018,hg/ha,213072,Fc,Calculated data
3,QC,Crops,9,Argentina,5510,Production,515,Apples,2016,2016,tonnes,458908,NaN,Official data
4,QC,Crops,9,Argentina,5510,Production,515,Apples,2017,2017,tonnes,458908,NaN,Official data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,QC,Crops,231,United States of America,5419,Yield,388,Tomatoes,2017,2017,hg/ha,886625,Fc,Calculated data
62,QC,Crops,231,United States of America,5419,Yield,388,Tomatoes,2018,2018,hg/ha,968079,Fc,Calculated data
63,QC,Crops,231,United States of America,5510,Production,388,Tomatoes,2016,2016,tonnes,12877049,NaN,Official data
64,QC,Crops,231,United States of America,5510,Production,388,Tomatoes,2017,2017,tonnes,11141862,NaN,Official data
65,QC,Crops,231,United States of America,5510,Production,388,Tomatoes,2018,2018,tonnes,12612139,NaN,Official data

Informacoes sobre

Renomear os titulos das colunas

In [6]:
df.columns

Index(['Domain Code', 'Domain', 'Area Code', 'Area', 'Element Code', 'Element',
       'Item Code', 'Item', 'Year Code', 'Year', 'Unit', 'Value', 'Flag',
       'Flag Description'],
      dtype='object')

In [7]:
df = pd.DataFrame(df)

In [10]:
df.rename(columns={'Domain Code':'C√≥digo do Dom√≠nio', 'Domain':'Dom√≠nio', 'Area Code':'C√≥digo de √Årea', 'Area':'√Årea', 'Element Code':'C√≥digo do Elemento', 'Element':'Elemento', 'Item Code':'Item do C√≥digo', 'Item':'Item', 'Year Code':'C√≥digo do Ano', 'Year':'Ano', 'Unit':'Unidade', 'Value':'Valor', 'Flag':'Sinalizador', 'Flag Description':'Descri√ß√£o da Sinalizador'})

,C√≥digo do Dom√≠nio,Dom√≠nio,C√≥digo de √Årea,√Årea,C√≥digo do Elemento,Elemento,Item do C√≥digo,Item,C√≥digo do Ano,Ano,Unidade,Valor,Sinalizador,Descri√ß√£o da Sinalizador
0,QC,Crops,9,Argentina,5419,Yield,515,Apples,2016,2016,hg/ha,223912,Fc,Calculated data
1,QC,Crops,9,Argentina,5419,Yield,515,Apples,2017,2017,hg/ha,235386,Fc,Calculated data
2,QC,Crops,9,Argentina,5419,Yield,515,Apples,2018,2018,hg/ha,213072,Fc,Calculated data
3,QC,Crops,9,Argentina,5510,Production,515,Apples,2016,2016,tonnes,458908,NaN,Official data
4,QC,Crops,9,Argentina,5510,Production,515,Apples,2017,2017,tonnes,458908,NaN,Official data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,QC,Crops,231,United States of America,5419,Yield,388,Tomatoes,2017,2017,hg/ha,886625,Fc,Calculated data
62,QC,Crops,231,United States of America,5419,Yield,388,Tomatoes,2018,2018,hg/ha,968079,Fc,Calculated data
63,QC,Crops,231,United States of America,5510,Production,388,Tomatoes,2016,2016,tonnes,12877049,NaN,Official data
64,QC,Crops,231,United States of America,5510,Production,388,Tomatoes,2017,2017,tonnes,11141862,NaN,Official data
65,QC,Crops,231,United States of America,5510,Production,388,Tomatoes,2018,2018,tonnes,12612139,NaN,Official data